services:

  api:
    build: ./api
    container_name: threat-api
    ports:
      - "8000:8000"

  alert-pipeline:
    build: ./alert-pipeline
    container_name: alert-pipeline
    depends_on:
      - redis

  postgres:
    image: postgres:16

  redis:
    image: redis:7

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana