name: CI Pipeline

on:
  push:
    branches:
      - dev
      - team-2

  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verify Docker Compose File
        run: |
          echo "Checking docker-compose.yml"
          test -f docker-compose.yml